### PRODUTO
GET http://localhost:8080/produto

###
GET http://localhost:8080/produto/1

###
POST http://localhost:8080/produto
Content-Type: application/json

{
    "nome": "Notebook Samsung xxxx",
    "descricao": "Core i9 xxxxMemória",
    "quantidade": 10,
    "preco": 10.99
}

###

###
PUT http://localhost:8080/produto/7
Content-Type: application/json

{
    "nome": "Notebook Dell",
    "descricao": "Core i9 Memória 32GB"
}

###

###
DELETE http://localhost:8080/produto/1
Content-Type: application/json